name: Vitals
main: org.michalpol.Vitals.Vitals
version: 0.0.4
commands:
   vitals:
      description: Checks [player] Vitals in [mode] (all-all players, p - picked player).
      usage: |
            /vitals [mode] [player]