name: BuyXP
author: michalpol
main: org.michalpol.BuyXP.BuyXP
version: 0.0.4
depend: [Vault]
commands:
   buyxp:
      description: Buys [amount] of experience points.
      usage: |
            /buyxp [amount]