name: ItemDurability
main: org.michalpol.ItemDurability.ItemDurability
version: 0.0.9
commands:
   dur:
      description: Checks item durability (In Hand).
      usage: |
            /dur [mode]